source /Users/SumitAsok/Dropbox/arena/gist/zshrc/print_hello.sh
source /Users/SumitAsok/Dropbox/arena/gist/zshrc/zsh.sh
source /Users/SumitAsok/Dropbox/arena/gist/zshrc/colours.sh
source /Users/SumitAsok/Dropbox/arena/gist/zshrc/git.sh
source /Users/SumitAsok/Dropbox/arena/gist/zshrc/django.sh
source /Users/SumitAsok/Dropbox/arena/gist/zshrc/beep.sh
source /Users/SumitAsok/Dropbox/arena/gist/zshrc/py.sh
source /Users/SumitAsok/Dropbox/arena/gist/zshrc/note.sh
source /Users/SumitAsok/Dropbox/arena/gist/zshrc/go.sh
source /Users/SumitAsok/Dropbox/arena/gist/zshrc/aliases.sh
source /Users/SumitAsok/Dropbox/arena/gist/zshrc/print_done.sh
